### ISSUE TITLE
Call recordings get mutilated when call is transfered

### ISSUE THREAD

**Issue by rbetancor** [irontec/ivozprovider#1177] opened 2019-11-08 08:54 UTC
### Description

When you have setup a DDI to record all incoming calls, and that incoming call get answered by some extension than then transfer the call to another vPBX endpoing, the recording get mutilated since the moment it get transfered, you been able only to listen to the incoming party.
Before the call get transfered or if the call is not transfered at all, the call get perfectly recorded.

---

- IvozProvider version:  2.12 2.12.1 20191016.2258 0 

- Related sections: 
    - [ ] SIP & Telephony
    - [X] vPBX Functionalities
    - [ ] Billing & Invoicing
    - [ ] Web Interface
    - [ ] API
    - [ ] Other

### Troubleshooting
Do an incoming call to a DDI set to be recorded, than transfer that call to another vPBX endpoint.

### Additional Information
Also the music on hold that is reproduced till the transfer is complete, get a very, very bad quality on the recording.

**Comment by Kaian** [comment] 2020-11-11 11:00
Hi @rbetancor 

I was unable to reproduce this on latest version of IvozProvider.

DDI recordings are done in ProxyTrunks, so things done by users should not affect their streams at all.

Carrier -> ProxyTrunks -> ApplicationServer -> ProxyUsers -> User

The recorded streams should be the one between Carrier and ProxyTrunks that should not change no matter what users do in their the right side of that diagram. 


Does this problem still exist?

Thanks!

**Comment by Kaian** [comment] 2021-04-06 08:22
A long time has past, but we were able to reproduce this issue. The problem was related with multime SSRC changes (multiple stream sources) in the same call, so in some cases more than a call transfer was required.

It should be fixed in 2.17.1

Thanks!

**Closed by Kaian** 2021-04-06 08:22 UTC
Labels: * artemis *, agis
