### ISSUE TITLE
Voicemail message from pbx, not receiving email with voicemail

### ISSUE THREAD

**Issue by gil-obradors** [irontec/ivozprovider#933] opened 2019-03-27 07:38 UTC
This is a PBX client.  An extension with call forwarding direct to voicemail. All done, listening locution...saving msg and voice file.
The problem is that I have not recived the voicemail to configured mail.  ( user has email configured)
May be I must configure an outgoing mail account?

I attach some log:

```
Mar 26 22:21:03 sip01 asterisk[678]: VERBOSE[31807][C-00000007]: config.c:2194 in config_text_file_load: Parsing '/opt/irontec/ivozprovider/storage/asterisk/spool/voicemail/company1/user34/INBOX/msg0000.txt': Found
Mar 26 22:21:03 sip01 systemd[1]: Starting Run Ivozprovider CDR mixer...
Mar 26 22:21:03 sip01 asterisk[678]: VERBOSE[31807][C-00000007]: res_agi.c:4309 in run_agi: <PJSIP/proxytrunks-0000000c>AGI Script agi://127.0.0.1:4573/fastagi-runner.php?command=dialplan/userstatus completed, returning 4
Mar 26 22:21:03 sip01 asterisk[678]: VERBOSE[31807][C-00000007]: pbx.c:4359 in __ast_pbx_run: Spawn extension (call-user, 107, 3) exited non-zero on 'PJSIP/proxytrunks-0000000c'
Mar 26 22:21:03 sip01 run-billable-calls[31824]: BillableCall migration done!
Mar 26 22:21:03 sip01 systemd[1]: Started Run Ivozprovider CDR mixer.
Mar 26 22:21:04 sip01 [31821]: request.INFO: Matched route "_voicemail_sender". {"route":"_voicemail_sender","route_parameters":{"_controller":"kernel:handleRequestAction","_route":"_voicemail_sender"},"request_uri":"http://localhost/voicemail/sender","method":"GET"} []
Mar 26 22:21:04 sip01 [31821]: security.INFO: Populated the TokenStorage with an anonymous Token. [] []
Mar 26 22:21:04 sip01 [31821]: php.INFO: User Deprecated: The "Ivoz\Core\Domain\Service\DomainEventPublisher" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Ivoz\\Core\\Domain\\Service\\DomainEventPublisher\" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead. at /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:282)"} []
Mar 26 22:21:04 sip01 [31821]: php.INFO: User Deprecated: Service identifiers will be made case sensitive in Symfony 4.0. Using "voicemail\sender" instead of "Voicemail\Sender" is deprecated since Symfony 3.3. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Service identifiers will be made case sensitive in Symfony 4.0. Using \"voicemail\\sender\" instead of \"Voicemail\\Sender\" is deprecated since Symfony 3.3. at /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php:516)"} []
Mar 26 22:21:04 sip01 [31821]: php.CRITICAL: Call to a member function error() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function error() on null at /opt/irontec/ivozprovider/asterisk/agi/app/MicroKernel.php:97)"} []
Mar 26 22:21:04 sip01 asterisk[678]: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function error() on null in /opt/irontec/ivozprovider/asterisk/agi/app/MicroKernel.php:97
Mar 26 22:21:04 sip01 asterisk[678]: Stack trace:
Mar 26 22:21:04 sip01 kernel: [568175.314547] voicemail-sende[31821]: segfault at 8 ip 00007f8fe4284e24 sp 00007ffecfc47b90 error 4 in mailparse.so[7f8fe427d000+d000]
Mar 26 22:21:04 sip01 asterisk[678]: #0 /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): MicroKernel->handleRequestAction()
Mar 26 22:21:04 sip01 asterisk[678]: #1 /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
Mar 26 22:21:04 sip01 asterisk[678]: #2 /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
Mar 26 22:21:04 sip01 asterisk[678]: #3 /opt/irontec/ivozprovider/asterisk/agi/bin/voicemail-sender.php(15): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
Mar 26 22:21:04 sip01 asterisk[678]: #4 {main}
Mar 26 22:21:04 sip01 asterisk[678]:   thrown in /opt/irontec/ivozprovider/asterisk/agi/app/MicroKernel.php on line 97
Mar 26 22:21:05 sip01 asterisk[678]: Segmentation fault (core dumped)
```
```
/usr/lib/asterisk/modules# ls /opt/irontec/ivozprovider/storage/asterisk/spool/voicemail/company1/user34/INBOX/msg0000.
msg0000.txt  msg0000.wav 
:/usr/lib/asterisk/modules# cat /opt/irontec/ivozprovider/storage/asterisk/spool/voicemail/company1/user34/INBOX/msg0000.txt
;
; Message Information file
;
[message]
origmailbox=user34
context=call-user
macrocontext=
exten=107
rdnis=107
priority=3
callerchan=PJSIP/proxytrunks-0000000c
callerid="proves" <+***********>
origdate=Tue Mar 26 09:20:55 PM UTC 2019
origtime=1553635255
category=
msg_id=1553635255-00000000
flag=
duration=7

:/usr/lib/asterisk/modules# ls /opt/irontec/ivozprovider/storage/asterisk/spool/voicemail/company1/user34/INBOX/
msg0000.txt  msg0000.wav

:/usr/lib/asterisk/modules# ls /opt/irontec/ivozprovider/storage/asterisk/spool/voicemail/company1/user34/
INBOX/  Old/    tmp/    Urgent/
```

packages: ivozprovider 2.9~2.9.3~20190318.1934~33c273a+artemis

**Comment by Kaian** [comment] 2019-03-27 08:40
Hi @gil-obradors 

Voicemails are sent using local MTA, so you must configure some postfix or exim to actually sent the email to its final destination.

The script in charge of sending the email is `/opt/irontec/ivozprovider/asterisk/agi/bin/voicemail-sender.php` and, if the script crashes, asterisk usually leaves a temporary file in /tmp/astmail-XXX or something like that.

You can retry the script by running

```
cat /tmp/astmail-xxxxx | /opt/irontec/ivozprovider/asterisk/agi/bin/voicemail-sender.php
```
To get better logs on what's the problem. If you can provide those logs it would help debugging this.

Regards!

**Comment by gil-obradors** [comment] 2019-03-27 11:55
Solved!
The reason was that I did not have the MTA Local configured (postfix)
-voicemail-sender.php working fine
-notifications are sent automatically after hangup in voicemails.


Great!
Thanks

**Comment by Kaian** [comment] 2019-03-27 12:00
You welcome!

The log lines referring to segfaults and crashes scares me a bit. We didn't see anything like that in our environments.

Anyway, if it works for you, I'll close this.

**Closed by Kaian** 2019-03-27 12:00 UTC
Labels: * artemis *, +bug, as

**Comment by gil-obradors** [comment] 2019-03-27 12:06
Maybe because I have not installed postfix nor exim? (not expressed well last msg)
I have installed and configured,

**Comment by Kaian** [comment] 2019-03-27 12:20
I was talking about these:

```
Mar 26 22:21:04 sip01 asterisk[678]: PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function error() on null in /opt/irontec/ivozprovider/asterisk/agi/app/MicroKernel.php:97
Mar 26 22:21:04 sip01 asterisk[678]: Stack trace:
Mar 26 22:21:04 sip01 kernel: [568175.314547] voicemail-sende[31821]: segfault at 8 ip 00007f8fe4284e24 sp 00007ffecfc47b90 error 4 in mailparse.so[7f8fe427d000+d000]
Mar 26 22:21:04 sip01 asterisk[678]: #0 /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): MicroKernel->handleRequestAction()
Mar 26 22:21:04 sip01 asterisk[678]: #1 /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
Mar 26 22:21:04 sip01 asterisk[678]: #2 /opt/irontec/ivozprovider/library/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
Mar 26 22:21:04 sip01 asterisk[678]: #3 /opt/irontec/ivozprovider/asterisk/agi/bin/voicemail-sender.php(15): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
Mar 26 22:21:04 sip01 asterisk[678]: #4 {main}
Mar 26 22:21:04 sip01 asterisk[678]:   thrown in /opt/irontec/ivozprovider/asterisk/agi/app/MicroKernel.php on line 97
Mar 26 22:21:05 sip01 asterisk[678]: Segmentation fault (core dumped)
```

I thing that shouldn't happen, but as I mentioned, I've never seen those errors before. 

If those errors still arise, maybe the problem is elsewhere.

Regards

**Comment by gil-obradors** [comment] 2019-05-14 14:37
Solved, It was a problem with firewall, 25 tcp closed handmade for me , my fault.


Thank you
