### ISSUE TITLE
Create Virtual PBX

### ISSUE THREAD

**Issue by pvenzin** [irontec/ivozprovider#1154] opened 2019-10-20 12:37 UTC
I have installed Artemis Release (Standalone). But on creating Virtual PBXs i becomes following error "undefined error". I can't no see the builded Virtual PBX but if i create another Virtual PBX with the same Name i become the error "duplicate key".

I can't find any record for this company in the table companies.

**Comment by Kaian** [comment] 2019-10-21 08:05
Hi @pvenzin 

Please, try to use Github Issue templates, otherwise isses may end closed unanswered.

Not controlled errors are displayed as _Undefined errors_ in administation portal. Try the following in order to get the actual error:

- Check journal logs by running `journalctl -f` while you reproduce the issue
- Check apache logs in /var/log/apache2/error.log  while you reproduce the issue
- Try enabling development mode in your portal by editing /opt/irontec/ivozprovider/web/admin/public.index.php and adding `putenv("APPLICATION_ENV=development");` before the last require line (something like [this file](https://github.com/irontec/ivozprovider/blob/bleeding/web/admin/public/dev.php) does.

This should put some light to the error.

Regards

**Comment by pvenzin** [comment] 2019-10-21 08:15
Hi @Kaian 
In development Mode i becomes following error:


![image](https://user-images.githubusercontent.com/33653308/67187940-a0abf980-f3eb-11e9-98c8-6593c06baf7b.png)

![image](https://user-images.githubusercontent.com/33653308/67187924-98ec5500-f3eb-11e9-8426-183e1bd5504f.png)

**Comment by Kaian** [comment] 2019-10-21 09:14
You have found where to dig for the error, but I'm bot sure if that's a full log, it seems it only a partial backtrace from #41 to #25 and does not even contain the error message. 

Please attach the full error log. You can use a pastebin link if the text is too big.

**Comment by pvenzin** [comment] 2019-10-21 10:12
journalctl:sshd[5011]: PAM 2 more authentication failures; logname= uid=0 euid=0 tty=ssh ruser= rhost=49.88.112.71  user=root
Oct 21 12:06:19 vmi308239 changelog[26222]: changelog.INFO: CommandWasExecuted > Ivoz\Core\Application\Service\DataGateway::persist(["\\Ivoz\\Provider\\Domain\\Model\\Company\\Company",{"type":"vpbx","name":"mami","domainUsers":"mami.sipstar.ch","nif":"12345678-Z","distributeMethod":"hash","maxCalls":"10","postalAddress":"Postal address","postalCode":"PC","town":"Town","province":"Province","countryName":"Country","ipfilter":"0","onDemandRecord":0,"onDemandRecordCode":null,"externallyextraopts":null,"recordingsLimitMB":null,"recordingsLimitEmail":null,"billingMethod":"postpaid","balance":0,"showInvoices":false,"id":null,"language":"#1","mediaRelaySets":null,"defaultTimezone":"#145","brand":"#2","domain":null,"applicationServer":null,"country":"#70","currency":null,"transformationRuleSet":"#70","outgoingDdi":null,"outgoingDdiRule":null,"voicemailNotificationTemplate":null,"faxNotificationTemplate":null,"invoiceNotificationTemplate":null,"callCsvNotificationTemplate":null,"extensions":null,"ddis":null,"friends":null,"companyServices":null,"terminals":null,"ratingProfiles":null,"musicsOnHold":null,"recordings":null,"relFeatures":[],"relCodecs":null,"relRoutingTags":null}]) [] []
Oct 21 12:06:19 vmi308239 changelog[26222]: changelog.INFO: EntityWasCreated > Ivoz\Provider\Domain\Model\Domain\Domain#19 > {"domain":"mami.sipstar.ch","pointsTo":"proxyusers","description":"mami proxyusers domain","id":19} [] []
Oct 21 12:06:20 vmi308239 changelog[26222]: Exception captured [500]: Gearmand return code error (0) # /opt/irontec/ivozprovider/library/Ivoz/Core/Infrastructure/Domain/Service/Gearman/Jobs/AbstractJob.php (94)

Apache Log:
[Mon Oct 21 12:10:47.647166 2019] [:error] [pid 5108] [client 194.230.XXX.XX:53351] PHP Warning:  GearmanClient::doBackground(): send_packet(GEARMAN_COULD_NOT_CONNECT) Failed to send server-options packet -&gt; libgearman/connection.cc:433 in /opt/irontec/i$

**Comment by pvenzin** [comment] 2019-10-21 11:50
Sorry closed.

**Comment by Kaian** [comment] 2019-10-21 13:06
Looks like your gearman-job-server is not running.

Did you rebooted after installation?

Regards

**Comment by pvenzin** [comment] 2019-10-21 13:15
gearman was not started, thanks a lot

**Comment by pvenzin** [comment] 2019-10-21 13:16
Looks like your gearman-job-server is not running.

Did you reboot after installation?

Regards

**Comment by Kaian** [comment] 2019-10-21 13:21
You can run `systemctl start gearman-job-server`, but it would be nice to know why it didn't started after rebooting.

**Comment by Kaian** [comment] 2019-10-23 15:48
Any news with this problem? Did you found why your gearman service was not running?

**Comment by Kaian** [comment] 2019-11-04 09:17
I'm closing this as an enviroment related problem.

Thanks for reporting!

**Closed by Kaian** 2019-11-04 09:17 UTC
Labels: * artemis *, web/admin
