### ISSUE TITLE
error prepaid accounts

### ISSUE THREAD

**Issue by boxlostdvdr** [irontec/ivozprovider#1690] opened 2021-12-21 02:28 UTC
Friends, I was about to use the ivoz provider in production on my provider, I have already adjusted incoming numbers by sending calls to the IVR, created VPBX clients, etc.
But I found a problem with prepaid accounts, I can make calls and talk normally, but the balance in Billing>>Prepaid Balances doesn't change at all, and in Calls>>External calls it only shows the call duration, Price and Cost are blank, rates are created correctly!
If you need any logs or access just let me know, as the platform is not in production yet!
Thanks
Regards

IvozProvider version:  2.19~2.19.0~20211109.34

**Comment by Kaian** [comment] 2021-12-22 09:33
Please, use provided templates while reporting bugs, otherwise the issues may be closed automatically.

Looks like this is a problem in your enviroment as we can not reproduce this issue in our test environments.

Be sure your cgrates service is running and your carriers are not marked as Externally Rated, otherwise no tarification will be done.

If you need further assistance, feel free to contact our comercial support at comercial@irontec.com

Regards

**Comment by boxlostdvdr** [comment] 2022-01-13 16:21
Friends, do you have a scheduled date for the correction?
Thanks and Regards

**Closed** 2024-11-12 08:17 UTC
Labels: * artemis *, +wontfix
