### ISSUE TITLE
option to add registered user's IP as authorized?

### ISSUE THREAD

**Issue by syadnom** [irontec/ivozprovider#227] opened 2017-07-25 22:08 UTC
For customers with dynamic public IP addresses, can their IP be automatically added to the allow list by any method?  For instance, if they complete a successful registration within x number of attempts then allow, otherwise drop?  Or is there a better mechanism for dynamic customers that isn't disabling this security measure?

**Comment by Kaian** [comment] 2017-07-26 09:43
Hi @syadnom 

Since version 1.4.0, those users with dynamic IP address (because they usually connect from external networks) are what we call _road warriors_. When a user is marked as _road warrior_ it's allowed to place a limited number of external calls from any IP address (You can edit this setting in Users' edit screen).

More info can be found [here](https://irontec.github.io/ivozprovider/en/security/index.html#roadwarrior-users)

Best regards,

**Comment by syadnom** [comment] 2017-07-27 21:09
This isn't quite my scenario.   The cost to get a static wan IP is getting quite high, and some of my customers don't get their own public IP they are in a carrier grade NAT environment and they can get any number of public addresses.   Call limits probably aren't going to cut it for them.

**Comment by syadnom** [comment] 2017-07-27 21:32
Might you consider the following

Allow x number of registration attempts from any IP (GEOIP still applies) and if no successful login, then block.  If there is a successful login, add to allow list.

If this isn't within the scope, I would just disable the feature and handle it via fail2ban but I'd have to scrape auth logs to add IP's to the allow list.  This is what I'm doing on my current platform.

**Comment by cruzccl** [comment] 2017-09-21 15:44
Hi @syadnom ,

We understand your concern and in those scenarios we will use [roadwarrior users](https://irontec.github.io/ivozprovider/en/security/index.html#roadwarrior-users) as recommended by @Kaian .

You could have the mechanism turned on in the company without any IP address (as it keeps changing) and limit the number of outgoing calls of each user to 1/2/3.

With this configuration the security mechanism achieves the goal it was designed for: even though you have some valid credentials, you can't use them to place hundreds of calls, you can call as a normal user would do (1/2/3 parallel calls).

This way toll fraud is made much harder than if you would just disable the IP check.

Regards,

**Closed** 2018-02-02 16:18 UTC
Labels: +question, users
