### ISSUE TITLE
Frontend isuee Residential advanced config recordings box

### ISSUE THREAD

**Issue by gil-obradors** [irontec/ivozprovider#1011] opened 2019-06-11 09:34 UTC
When edit residential client, show more settings.
I'm going to add invoice data, basic config..... but I can't save the new config because I need to put the code for on-demand call recording.
However by default on-demand is disabled but is asking for a code  ( as selected DTMF)

I need to check  on-demand -> using INFO    and again  on-demand -> disabled
Then disappears and I can save

2.10~2.10.0~20190430.2009~1db7b82+artemis all

**Comment by Kaian** [comment] 2019-06-11 09:54
Hi @gil-obradors 

Thanks for reporting!!

I am able to reproduce this problem, but It's a bit strange it doesn't happen in vPBX edit screen, that also uses those two fields. Because there is a workaround, we'll try to fix this whenever have some spare time.

Regards!

**Comment by Kaian** [comment] 2019-07-26 10:00
This will be fixed in next release.

Thanks for reporting!

**Closed by Kaian** 2019-07-26 10:00 UTC
Labels: * artemis *, +bug, web/admin
