### ISSUE TITLE
iso: failed to install if mysql pass has spaces

### ISSUE THREAD

**Issue by ascalotoru** [irontec/ivozprovider#1] opened 2016-11-17 13:52 UTC
The 64 bits ISO crash in the "Select and install software" step.
The log shows:
`Nov 17 13:33:48 in-target: dpkg: error al procesar el paquete ivozprovider-scheme (--configure):`
I'm perfoming the install in VirtualBox 5.0.24 on Ubuntu 16.04.
I attach a screenshot of the log
![virtualbox_ivoz_17_11_2016_14_45_06](https://cloud.githubusercontent.com/assets/708756/20391833/62efcf0a-acd5-11e6-9fb0-98b3a4c9b541.png)

**Comment by Kaian** [comment] 2016-11-17 14:34
Hi @ascalotoru 

I need a bit more information: 

 * Are you testing 1.0 iso or 1.1 nighly build?
 * From the screenshot: Do your mysql password contain an space?

Thanks for the feedback and taking the time to test the ISO!

**Comment by ascalotoru** [comment] 2016-11-17 14:59
Hello @Kaian 

Is 1.0 stable and yes, my mysql password contains a space.
I tried with a password with no spaces and it worked.

**Comment by Kaian** [comment] 2016-11-17 15:21
Hi, 

  I have updated the install scripts to handle those passwords.
  Saldy this change will only apply to 1.1 ISOs, so I'll give it a try to the next nightly :)
  
   I'll rename the issue now we know where the problem is.

Thanks a lot @ascalotoru !!

**Comment by Kaian** [comment] 2016-12-26 14:07
Fixed in latest 1.1 standalone iso 

Thanks for reporting!!

**Closed by Kaian** 2016-12-26 14:07 UTC
Labels: packaging
